# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
{{- if .Values.externalSecrets.enabled }}
{{- $dataFrom := .Values.externalSecrets.dataFrom | required "externalSecrets.dataFrom is required." }}
{{- $targetName := .Values.externalSecrets.target.name | required "externalSecrets.target.name is required." }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "lfx-changelog.externalSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-changelog.labels" . | nindent 4 }}
  {{- with (include "lfx-changelog.externalSecretAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "lfx-changelog.secretStoreName" . }}
    kind: SecretStore
  target:
    name: {{ $targetName }}
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy }}
    {{- if .Values.externalSecrets.target.template }}
    template:
      {{- toYaml .Values.externalSecrets.target.template | nindent 6 }}
    {{- end }}
  dataFrom:
    {{- toYaml $dataFrom | nindent 4 }}
{{- end }}
