# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
{{- if .Values.externalSecrets.enabled }}
{{- $provider := .Values.externalSecrets.provider | required "externalSecrets.provider is required." }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "lfx-changelog.secretStoreName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-changelog.labels" . | nindent 4 }}
  {{- with (include "lfx-changelog.secretStoreAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  provider:
    {{- toYaml $provider | nindent 4 }}
{{- end }}
